config/routes.rb
Spellhelper::Application.routes.draw do
  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :announcer do
    member do
      get 'shuffle'
    end
  end

  root :to => 'announcer#index'

end

app/models/list.rb
class List < ActiveRecord::Base
	has_many :words, through: :list_words
	has_many :list_words

	def shuffle
    randomized_array = (1..list_words.count).to_a.shuffle
    list_words.each_index{ |index| list_words[index].update_attribute(:order, randomized_array[index]) }
	end

end

app/models/list_word.rb
class ListWord < ActiveRecord::Base
	belongs_to :word
	belongs_to :list
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/word.rb
class Word < ActiveRecord::Base
	has_many :lists, through: :list_words
	has_many :list_words

	def pronunciation_url
		"http://ahdictionary.com/application/resources/wavs/#{pronunciation}.wav"
	end
end

app/controllers/announcer_controller.rb
class AnnouncerController < ApplicationController
  before_filter :authenticate_user!
  before_filter :current_list_id

  def shuffle
    session[:current_list] = params[:id]
    List.find(params[:id]).shuffle

    redirect_to announcer_path(1)
	end

	def index
    @lists = List.all
	end

	def show
    @wordlist_index = params[:id].to_i
    @wordlist_index = 1 if(@wordlist_index == 0)

    @wordlist_count = ListWord.find_all_by_list_id(@current_list_id).count
    @word = ListWord.find_by_list_id_and_order(@current_list_id, @wordlist_index).word
	end

private
  def current_list_id
    @current_list_id = session[:current_list]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/helpers/announcer_helper.rb
module AnnouncerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/announcer/index.html.erb
<% @lists.each do |list| %>
<div class="list-info"><%= link_to list.name, shuffle_announcer_path(list.id) %></div>
<% end %>

app/views/announcer/show.html.erb
<div id="container">
  <div id="header">
    <div id="home" class="header-elements"><%= link_to "Home", "/announcer" %></div>
    <div id="shuffle" class="header-elements"><%= link_to "Shuffle", shuffle_announcer_path(@current_list_id) %></div>
    <div id="wordlist_index" class="header-elements"><%= @wordlist_index %>/<%= @wordlist_count %></div>
  </div>

  <div id="word-container">
    <div id="word"><%= @word.spelling %></div>
  </div>

  <div id="footer">

    <div id="prev" class="footer-elements">
      <% if @wordlist_index > 1 %>
      <%= link_to "Prev", announcer_url(@wordlist_index-1) %>
      <% end %>
    </div>


    <div id="listen" class="footer-elements">
      <%= link_to "Pronounce", @word.pronunciation_url, target: "_blank" %>
    </div>

    <div id="reveal" class="footer-elements">
      <%= link_to "Reveal", "#", id: "reveal-link" %>
    </div>


    <div id="next" class="footer-elements">
      <% if @wordlist_index <= @wordlist_count -1 %>
        <%= link_to "Next", announcer_url(@wordlist_index+1) %>
      <% end %>
    </div>

  </div>
</div>
<%= javascript_tag do %>
	$("#word").hide();
  $("#reveal").click( function(){
  	if($("#word").hasClass("revealed")){
  		$("#word").hide();
  		$("#reveal-link").text("Reveal");
  		$("#word").removeClass("revealed")
  	}else{
  		$("#word").show();
  		$("#reveal-link").text("Hide");
  		$("#word").addClass("revealed")
  	}
	});
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spellhelper</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= flash[:notice] %></p>
<p class="alert"><%= flash[:alert] %></p>

<%= yield %>

</body>
</html>